version: 1.0.{build}
branches:
  only:
  - master
build_script:
- cmd: >-
    cd build_automation

    psake.cmd
test: off
artifacts:
- path: artifact/dist/PSakeSampler.ConsoleApp.7z
- path: artifact/dist/PSakeSampler.WebApp.7z
- path: artifact/dist/*.nupkg
